# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^doc/.*\.rst$
    -   id: end-of-file-fixer
        exclude: ^doc/.*\.rst$
    -   id: check-yaml
        exclude: ^doc/.*\.rst$
    -   id: check-added-large-files
        exclude: ^doc/.*\.rst$
        args: ['--maxkb=10000']
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.941
#    hooks:
#        - id: mypy
        #   additional_dependencies: [pydantic]  # add if use pydantic
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
