name: Submit a New Dataset
description: Use this template to submit a new dataset.
title: "[Dataset]: "
labels: ["dataset-submission"]
body:
  - type: input
    id: dataset_name
    attributes:
      label: Dataset Name
      description: Provide a name for the dataset.
      value: "e.g., Human Activity Recognition Dataset"

  - type: textarea
    id: paper_reference
    attributes:
      label: Paper & authors references
      description: Provide a name of the associated paper with the relevant bibtex
      value: "e.g., @article{simonetto2024constrained,
     title={Constrained Adaptive Attack: Effective Adversarial Attack Against Deep Neural Networks for Tabular Data},
     author={Simonetto, Thibault and Ghamizi, Salah and Cordy, Maxime},
     journal={arXiv preprint arXiv:2406.00775},
     year={2024}
   }"
  - type: input
    id: license
    attributes:
      label: License
      description: Specify the license under which the dataset is distributed.
      placeholder: "e.g., MIT, Apache 2.0, etc."

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description (Optional)
      description: Provide a detailed description of the dataset, if available.
      placeholder: "A more detailed explanation of the dataset."

  - type: textarea
    id: dataset_files
    attributes:
      label: Dataset files
      description: Provide a detailed description of the dataset, if available.
      value: "Insert here the URL for the dataset content and the code. You can also open a PR and associate it with this issue"


